image: node:11.15.0

pages:
  stage: deploy
  script:
    - npm ci
    - npx gatsby telemetry --disable
    - npx gatsby clean
    - npx gatsby build
  artifacts:
    paths:
      - public
  only:
    - master
