backend:
  name: gitlab
  repo: aadroher/gef
  auth_type: implicit
  app_id: 6a0450f42ec3213087bc3459fe4695ffb11e77e9aac312228dd95eab95197acc
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: activities_ca
    label: "Activitats (ca)"
    label_singular: "Activitat (ca)"
    folder: data/collections/activities
    filter:
      field: language
      value: ca
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - name: createdAt
        label: "Creat el"
        widget: datetime
      - name: language
        label: "Idioma"
        widget: select
        options:
          - label: "Català"
            value: ca
          - label: "Castellà"
            value: es
          - label: "Anglès"
            value: en
      - name: vivible
        label: "Visible"
        widget: boolean
      - name: "title"
        label: "Títol"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
